version: '3.8'

services:  
  db:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: "products"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres_pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
       - "postgres_products:/var/lib/postgresql/data"
       - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "5433:5432"
    restart: unless-stopped
volumes:
  postgres_products:
